# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sacha < Formula
  desc "Keyboard-first AWS TUI"
  homepage "https://github.com/Sachamama/sacha"
  version "0.1.9"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sachamama/sacha/releases/download/v0.1.9/sacha_0.1.9_darwin_amd64.tar.gz"
      sha256 "d8599e483971468c24cc54b8ebe510e05991337c58cbcce36e9b5163513dc6ed"

      def install
        bin.install "sacha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sachamama/sacha/releases/download/v0.1.9/sacha_0.1.9_darwin_arm64.tar.gz"
      sha256 "a2d2f821e790cd47c8e004b06f1431622c32c5e9bfd33c3851d3283aea687542"

      def install
        bin.install "sacha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sachamama/sacha/releases/download/v0.1.9/sacha_0.1.9_linux_amd64.tar.gz"
      sha256 "563e60ab8a60acba917f05717aa74c3cbad017af5f7ac180e77177d5df7757f5"
      def install
        bin.install "sacha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sachamama/sacha/releases/download/v0.1.9/sacha_0.1.9_linux_arm64.tar.gz"
      sha256 "bf3cae572593c990c3faf6010a98c7773461f9a98f2bf5f35d115625c2161ed2"
      def install
        bin.install "sacha"
      end
    end
  end

  test do
    system "#{bin}/sacha", "--version"
  end
end
